app:
  name: OJ
  addr: ":3000"

database:
  host: db
  port: 5432
  user: postgres
  password: 246266262
  name: oj

jwt:
  secret: "secret"
  minexpires: "3600"
  refreshkey: "refresh"
  refreshexpires: "720"

  sandbox:
    type: example

redis:
  host: redis
  port: 6379
  db: 0
